/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pwrlab_memomonitor_MonitorJNI */

#ifndef _Included_com_pwrlab_memomonitor_MonitorJNI
#define _Included_com_pwrlab_memomonitor_MonitorJNI
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_pwrlab_memomonitor_MonitorJNI
	* Method:    getTotalRamMBNative
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_com_pwrlab_memomonitor_MonitorJNI_getTotalRamMBNative
	(JNIEnv *, jclass);

	/*
	* Class:     com_pwrlab_memomonitor_MonitorJNI
	* Method:    getUsedRamMBNative
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_com_pwrlab_memomonitor_MonitorJNI_getUsedRamMBNative
	(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
